name: Build
on:
  workflow_call:  
    inputs:
      bundle:
        type: string
        required: true
        description: 'BUNDLE RELEASE NUMBER'
      prefix:
        type: string
        required: true
        description: 'PREFIX'
      build_type:
        type: string
        required: true
        description: 'BUILD TYPE'
      aws_region:
        type: string
        required: true
        description: 'aws_region'
      build_environment:
        type: string
        required: true
        description: 'build_environment'
      aws_account:
        type: string
        required: true
        description: 'aws_account'
