name: Build
on:
  workflow_call:  
    inputs:
      release:
        type: string
        required: true
        description: 'RELEASE NUMBER'
      prefix:
        type: string
        required: true
        description: 'PREFIX'
      build_type:
        type: string
        required: false
        description: 'BUILD TYPE'
      aws_region:
        type: string
        required: false
        description: 'aws_region'
      build_environment:
        type: string
        required: false
        description: 'build_environment'
      aws_account:
        type: string
        required: false
        description: 'aws_account'

env:
  BUNDLE: ${{ inputs.release }}
  REGISTRY: ghcr.io
  AWS_ACCOUNT: ${{ inputs.aws_account }}
  AWS_REGION: ${{ inputs.aws_region }}


jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: pnc-usdemo
    steps:
    - name: Echo Hello World
      env:
        ACTIONS_STEP_DEBUG: true
        BUNDLE: ${{ inputs.release }}
      run: echo ${{ inputs.release }} ${{ secrets.AWS_ACCOUNT }}
