name: Build
on:
  workflow_call:  
    inputs:
      bundle:
        type: string
        required: true
        description: 'BUNDLE RELEASE NUMBER'
      prefix:
        type: string
        required: true
        description: 'PREFIX'
      build_type:
        type: string
        required: false
        description: 'BUILD TYPE'
      aws_region:
        type: string
        required: false
        description: 'aws_region'
      build_environment:
        type: string
        required: false
        description: 'build_environment'
      aws_account:
        type: string
        required: false
        description: 'aws_account'
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Hello World
      env:
        BUNDLE: ${{ inputs.bundle }}
      run: echo ${{ inputs.bundle }}
