name: Build
on:
  workflow_call:  
    inputs:
      release:
        type: string
        required: true
        description: 'RELEASE NUMBER'
      prefix:
        type: string
        required: true
        description: 'PREFIX'
      aws_account:
        type: string
        required: false
        description: 'aws_account'
      aws_region:
        type: string
        required: false
        description: 'aws_region'
      client:
        type: string
        required: true
        description: 'Client'
      clm_fqdn:
        type: string
        required: false
        description: 'clm_fqdn'
      environment:
        type: string
        required: false
        description: 'Environment'

env:
  BUNDLE: ${{ inputs.release }}
  REGISTRY: ghcr.io
  AWS_ACCOUNT: ${{ inputs.aws_account }}
  AWS_REGION: ${{ inputs.aws_region }}


jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: pnc-usdemo
    steps:
    - name: Echo Hello World
      env:
        ACTIONS_STEP_DEBUG: true
        BUNDLE: ${{ inputs.release }}
      run: echo ${{ inputs.release }} /
           echo ${{ inputs.prefix }} /
           echo ${{ inputs.aws_region }} /
           echo ${{ inputs.aws_account }} /
           echo ${{ inputs.clm_fqdn }} /
           echo ${{ inputs.environment }} /
           echo ${{ inputs.client }} /
           echo ${{ secrets.AWS_ACCOUNT }}
