name: Build
on:
  workflow_call:  
    inputs:
      release:
        type: string
        required: true
        description: 'RELEASE NUMBER'
      prefix:
        type: string
        required: true
        description: 'PREFIX'
      aws_account:
        type: string
        required: true
        description: 'AWS ACCOUNT'
      aws_region:
        type: string
        required: true
        description: 'AWS REGION'
      client:
        type: string
        required: true
        description: 'CLIENT'
      clm_fqdn:
        type: string
        required: true
        description: 'CLM FQDN'
      environment:
        type: string
        required: false
        description: 'ENVIRONMENT'

env:
  BUNDLE: ${{ inputs.release }}
  REGISTRY: ghcr.io
  AWS_ACCOUNT: ${{ inputs.aws_account }}
  AWS_REGION: ${{ inputs.aws_region }}


jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.prefix }}
    steps:
    - name: Build PNC USDEMO [ RELEASE NO. ${{ github.event.inputs.release }} ]
      env:
        RELEASE: ${{ inputs.release }}
      run: echo ${{ inputs.release }} /
           echo ${{ inputs.prefix }} /
           echo ${{ inputs.aws_region }} /
           echo ${{ inputs.aws_account }} /
           echo ${{ inputs.clm_fqdn }} /
           echo ${{ inputs.environment }} /
           echo ${{ inputs.client }} /
           echo ${{ secrets.AWS_ACCOUNT }}
